# SPDX-FileCopyrightText: 2026 Gabriel Arazas <foodogsquared@foodogsquared.one>
#
# SPDX-License-Identifier: MIT

version = 1
SPDX-PackageName = "nixos-config-foodogsquared"

[[annotations]]
path = [
  "docs/website/**",
  "**/.terraform.lock.hcl",
  "**/flake.lock",
]
precedence = "closest"
SPDX-FileCopyrightText = "Gabriel Arazas<foodogsquared@foodogsquared.one>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [ "docs/website/static/**" ]
SPDX-FileCopyrightText = "Gabriel Arazas<foodogsquared@foodogsquared.one>"
SPDX-License-Identifier = "CC-BY-NC-SA-4.0"

[[annotations]]
path = [
  "**/*.json",
  "**/*.json",
  "**/*.bin",
  "**/*.bin",
]
precedence = "closest"
SPDX-FileCopyrightText = "Gabriel Arazas<foodogsquared@foodogsquared.one>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "tests/**"
precedence = "closest"
SPDX-FileCopyrightText = "Gabriel Arazas<foodogsquared@foodogsquared.one>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "templates/**"
SPDX-License-Identifier = "NONE"

[[annotations]]
path = "**/*.patch"
SPDX-FileCopyrightText = "Gabriel Arazas<foodogsquared@foodogsquared.one>"
SPDX-License-Identifier = "MIT"
