# SPDX-FileCopyrightText: 2024-2026 Gabriel Arazas <foodogsquared@foodogsquared.one>
#
# SPDX-License-Identifier: MIT

baseURL = "./"
defaultContentLanguage = "en"
title = "foodogsquared's homepage"
timeZone = "UTC"
disableKinds = [ "taxonomy", "sitemap", "robotstxt", "rss" ]
