grafana:
    secret_key: ENC[AES256_GCM,data:5JoRbeK72toeU8Brlz78qQ3nwdsWy77Iy1DUiWyVklJjOWqg8yYkTo0FfsqS3T1h9ElnloEYTFu9QYMXL8WDKg==,iv:V89PC/GPRESKKCdKDhgJ3kHYgNa/f8U7HWn9TVDnErM=,tag:w0JuY4EA5Xi4+rdcxbjAbA==,type:str]
sops:
    age:
        - recipient: age12uu6hgy44pvt2rawjgl2m8vdfcn820hxxlmkmgumfyeewswh29tq9asn94
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYOERMRTJuZ0dkVGk2bDRQ
            T2gyV3YwTXFMcHdtQWVzS0Z2bVU5OEp4bm5zClZPY3k1TC84SE5LYkVGMS9oQWhD
            Vmh2Rzg5ekhBQTQrRUs2bUw0QlpCVmcKLS0tIHN6NDRQQ3JhOE10Q2F3VmlVWml2
            Rk1XbXNLbVlyRGRkY2tCZHUzVzJ0VkEK0jXT5HSnx0NfctPjca/mfL2OlszTKEOe
            DwATvqOef8aJ/9hIuQYLHS7/E+9cLAGA0x4KZ0PslcV/Urj6oF6LxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T07:34:32Z"
    mac: ENC[AES256_GCM,data:vLolbqqhjWa0/7nYc/VdDBRyOExtdZ8P4gAa2yoeeosuQ2M9Gw7Vs5FYDyCXAcRmE4APidj8sgmb9DoXKZhYscnu4eBvdIW6GFbNM2W8UWz/PkETDa6Seb2QKnivQ/r4UpMu4kjjgIanXzzpiEUSiCxK5FTLjf1zhg+vtyQitQE=,iv:9Dow1vJd4i6IJ3fartsXG5c6UgeI9A+NXxwp4K3iFk8=,tag:11nf45Og+clyyWZbilTxiA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
