# SPDX-FileCopyrightText: 2024-2026 Gabriel Arazas <foodogsquared@foodogsquared.one>
#
# SPDX-License-Identifier: MIT

archivebox:
    env: ENC[AES256_GCM,data:2hvgRgz5z68dxiDEHeDaYu5PHylCQj+x16RMdoIi6YK6aPRct3Trsm/ZULpl70LoebAkgtVMMOyFvPbjFof4Y5tpVv63Z8FRdReoxvRgloCPaEXAPZkXDNk/rFNijko95g==,iv:SQMxr/i8HLkET3+wxVGHOS2iCJ72YUMUeSes0MaiJEA=,tag:SHspYDXJTecj3aOg+3KyRw==,type:str]
sonic:
    env: ENC[AES256_GCM,data:KHquVkOXBS2Rmg52E4qrtdDzFfs54lRMqMTaV5TWsAc+oKQi264=,iv:ERP/0fLD0hlARwhdT12pnelGR5TQmrHqc19+Z8yvjrk=,tag:Q1CSLLKcpiD/CC/s//e4cA==,type:str]
sops:
    age:
        - recipient: age1np3wdsudf9ruakyvgym48c0ygjs2f8uyshphlmswdta904h2f5zshr2rtr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArRHpqTlBBT21pZVgxT0hR
            Y3Z4c1M3bENRRlo5NjdHdjV1L2ZjQ0M1YTJzClVSbE05aVozQ205ZjFvenpwR2FP
            MTdhWGF4SmQzNXBFVXZHN2JCMjRpTGcKLS0tIHF2b256aUVXNW1Ed050a2ozbU9B
            Tnpvak9TK0FYQkg3eFFicmxWdGdQak0KwQLVIGnswwxhvhb0yYwPn1yqPd0gox4a
            VmxbVU0k168f1fy1Bua1qYrF67RRTiU+djBoRO59BJo4HHurrFQ3nA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-29T06:12:49Z"
    mac: ENC[AES256_GCM,data:Wn48uYXanjw3MVQp06589/68U6uhKhDRE1RSual5SHItQo3xJ0LPNH9Hjbc2fHfdxvBewrHE0lafy3iWi54YC8WXgH4vkLFKQp6lAX8FJ0tDMnuNfrqHY+7zFvxBB0wItO6Ayf0sjWOkKyS2Shhiu1B17ehVKi+n8XkWCP+cUwY=,iv:JMYP4wSDOY/QbDh29cFLlbWzS/SaArk1v3gQeZAXXQI=,tag:lygvigozC4aEH3Wb/KKYkw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
