ssh-key: ENC[AES256_GCM,data:byjQ4QobB9dN,iv:KOBlvOUfMYDxVQnUvhYD379aEXkcl5ZgKm//MgLWyrA=,tag:UTg9siZwOcIMOIq4q2xhdw==,type:str]
sops:
    age:
        - recipient: age12uu6hgy44pvt2rawjgl2m8vdfcn820hxxlmkmgumfyeewswh29tq9asn94
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3M0hiQ3RuMzV0QlBNNjNp
            K3V3c2wwK05tMzcweG9Vcm12Y2x6YUMrcTN3CkhOZkMxTnRJRFhrcDdnVlhOS2dK
            Z3doaDVtaWNQU28rWmM1NzBIdjgvbXcKLS0tIFdWa201WFpZSm1FOFdZTGhYMkJm
            Vm91amZpcFV0VjdYSDJqZWxPeGhUNkUK8+2ieqLjsaQpOTvMjLzJ+vIOAoq7buFt
            Ik8CKfw1MKGD6y5Bbmrmyfm1xB1aMllLkDMD+fQOZB7Idav5uC4Qig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T07:36:37Z"
    mac: ENC[AES256_GCM,data:sJfw3JD5Zi+lG72+kLK/GV5cZXq2Z4LaL36q4etE7a5wYCDC+/hMG4ZvN8pG+j/pZtBCu6UL4ckbxUhDyrC6HdeIC8Z62ZoWnSVRIj0hdzKXsw0iyTctFOgMDBw5GAU1ELatFtK8VrdCabDmzDIyctcuCmZ8PYFI18MFj37kBsc=,iv:o05wxtk4niMxFwZlg6eygqEx6Grbu09w3f0IG8LDTCE=,tag:UUdl4cQ5Zd9RwDLLP805yQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
