grafana:
    secret_key: ENC[AES256_GCM,data:VjPnvBpWpuqpWILoBB6L/mS0uoJokkn5e3xUrjuMubl6Mi7gFtL2beBsBUWmk5MDJr5qtalawRM/BkFuZe0eMQ==,iv:cl9KMsHDm93JESnBPgZ7jUV7R7PMS5+TkAc/FvqAtx4=,tag:Rl31LunYKzvf78OAWcJtNA==,type:str]
sops:
    age:
        - recipient: age1yftkhugwrdnlpl45lthrhvvk720zza2nd085sxvjcxg2guavz3kquktplx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYdXhDZ1BQQUc2Y29OUWNN
            bWF5eDZoRWhTNEp3TFpDcFV1eFlHd2VDTUIwCnMrMjZEUjNBbndBUjFXVEtFNlZT
            TEhCekI0OUQ0S2VyMUFaeFNHMlhYWkUKLS0tIFVUUWROeG1VVHFJRXFRd0xCS2la
            cHFXcVZBSEIzcGVkMmJvTEdjT3FmazAKXjjHy2xoSVzOGi9vAyULUmMHadS3c2I4
            nZVqezoHHN+qT+Djw/uZ55MNqZrXH8QttLhvW+/7aakXZhyUarGhug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T07:23:06Z"
    mac: ENC[AES256_GCM,data:1ZoDUp5jAguAEcbDMpDCtBWeQVSaxkNhS1lHvj5LCw+QinfApxh75i+L0eQow1cYpLchAmILpnd0q17B8W2Sf05WTxXFOUAN5ha8CnoMjwqKsPGj4gOHz47DSq0DT2T/fxQdPjtDQF1krYy7opmkwpNM/B7Xt1pnQE+yBrdn/OQ=,iv:QtVrw29BoQdRgF2vVX42HEcidzUi5ZDehfL/mOQ+xiw=,tag:F+6xEvlMA8bAdR53UIkTBw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
